source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UpLoadMoreControl_Example', :exclusive => true do
  pod "UpLoadMoreControl", :path => "../"
end

target 'UpLoadMoreControl_Tests', :exclusive => true do
  pod "UpLoadMoreControl", :path => "../"

  
end
